import 'dart:ui';

final Color background2 = Color(0xFF131313);
final Color background = Color(0xFF000000);
final Color button = Color(0xFF5c11bf);
final Color white = Color(0xFFffffff);
final Color sliverBackground = Color(0xFFfafafc);
final Color menu1Color = Color(0xFFf9d263);
final Color menu2Color = Color(0xFFf2603d);
final Color menu3Color = Color(0xFF04abe6);
final Color tabBarViewColor = Color(0xFFfdfdfd);
final Color startColor = Color(0xFFfdc746);
final Color subTitleText = Color(0xFF505050);
final Color loveColor = Color(0xFF00ace6);
final Color playerBlueBackground = Color(0xFFeeeffa);
final Color playerGreyBackground = Color(0xFFf2f2f2);
final Color textColor = Color(0xFF141417);
final Color button_background = Color(0xFF131313);
final Color button_text = Color(0xFFc6c6c6);
final Color close_button_background = Color(0xFF202020);
